### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by quasipickle** [nette/tracy#428]
Version: 2.7.5

### Bug Description
A Fatal error is caused by `Tracy\Helpers::editorUri()`:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Tracy\Helpers::editorUri() must be of the type string, bool given, called in /var/www/htdocs/ocv/app/libs/vendor/tracy/tracy/src/Tracy/BlueScreen/BlueScreen.php on line 402 and defined in /var/www/htdocs/ocv/app/libs/vendor/tracy/tracy/src/Tracy/Helpers.php:46
Stack trace:
#0 /var/www/htdocs/ocv/app/libs/vendor/tracy/tracy/src/Tracy/BlueScreen/BlueScreen.php(402): Tracy\Helpers::editorUri(false, false)
#1 [internal function]: Tracy\BlueScreen->Tracy\{closure}(Array)
#2 /var/www/htdocs/ocv/app/libs/vendor/tracy/tracy/src/Tracy/BlueScreen/BlueScreen.php(393): preg_replace_callback('#(\\w+\\\\[\\w\\\\]+\\...', Object(Closure), 'Cannot make sta...')
#3 /var/www/htdocs/ocv/app/libs/vendor/tracy/tracy/src/Tracy/BlueScreen/BlueScreen.php(120): Tracy\BlueScreen->formatMessage(Object(ErrorException))
#4 /var/www/htdocs/ocv/app/libs/vendor/tracy/tracy/src/Tracy/BlueScreen/BlueScreen.php(94): Tracy\BlueScreen->renderTemplate(Object(ErrorException), '/var/www/htdocs...')
#5 /var/w in /var/www/htdocs/ocv/app/libs/vendor/tracy/tracy/src/Tracy/Helpers.php on line 46
```

### Steps To Reproduce
The error Tracy was supposed to catch was that I had written a non-static class method that was the same name as a static class method in the parent class.

### Expected Behavior
The standard beautiful Tracy error message.

### Possible Solution
Looks like Reflection isn't finding the right class in BlueScreen.php

**Comment by dg** [comment]
fixed
